volumes:
  postgres-db:
  mongo-db:

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
    labels:
      traefik.enable: false
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      default:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 5G
    build:
      context: ..
      dockerfile: ./docker/mongo/Dockerfile
    environment:
      MONGODB_ROOT_USER: ${MONGO_USERNAME}
      MONGODB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_DATABASE: ${MONGO_DATABASE}
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME:-rs0}
      MONGODB_REPLICA_SET_KEY: ${MONGO_REPLICA_SET_KEY}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGO_ADVERTISED_HOSTNAME:-mongo}
    labels:
      - "traefik.enable=false"
    volumes:
      - mongo-db:/bitnami/mongodb
    ports:
      - "27019:27017"
    hostname: mongo
    networks:
      default:
        aliases:
          - mongo
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mongosh admin -u "$$MONGODB_ROOT_USER" -p "$$MONGODB_ROOT_PASSWORD" --authenticationDatabase admin --eval "db.adminCommand({ ping: 1 })" || exit 1',
        ]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 60s

  app:
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    env_file: ./../.env
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    command:
      sh -c "npx prisma migrate deploy --schema=prisma/schema.prisma && npx prisma db push --schema=prisma-mongo/schema.prisma && npm run start"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      default:
